### ISSUE TITLE
Logo proposal!

### ISSUE THREAD

**Issue by radudangratian** [Deadz/SteemRandomDraw#5]
Hello! As we talked on Discord I made that logo concept for you.I hope you will like it!

![random](https://user-images.githubusercontent.com/34451833/38332053-af9a0ed2-385d-11e8-9cd7-c23270388970.png)

Below you can find a Gdrive link with all the files that you need!
https://drive.google.com/open?id=1BiaUSxy3CGzhOVkGz4WeSmcFMJSRBgCX

Best Regards!

**Comment by Deadz** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/b9dfa6f4-4fd5-4148-b47e-ea2dace2b107-718f1d05-b967-4353-a095-2b3977789f87-v1.png?transparent=1&palette=1&width=246)

Wow, thank you so much. That's great. I added your logo in the website:)
